name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

env:
  workspace_path: "/builds/raymon/electronics"
  stm32cubeIDE_path: "/opt/st/stm32cubeide_1.17.0/stm32cubeide"
  project_name: "${{ github.event.repository.name }}"

jobs:
  build-job:
    name: Build Firmware
    runs-on: ubuntu-latest
    container:
      image: aminamani/ubuntu-raymon:22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find STM32CubeIDE folder
        run: |
          echo "build with STM32CubeIDE..."

          /opt/st/stm32cubeide_1.17.0/stm32cubeide \
          --launcher.suppressErrors \
          -nosplash \
          -application org.eclipse.cdt.managedbuilder.core.headlessbuild \
          -build all \
          -importAll /__w/SurenaHandMultiLayer/SurenaHandMultiLayer/firmware \
          -data /home/ws/


          