name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

env:
  stm32cubeIDE_path: "/opt/st/stm32cubeide_1.17.0/stm32cubeide"
  firmware_path: "${{ github.workspace }}/firmware"
  ws_path: "/home/ws/"

jobs:
  build-job:
    name: Build Firmware
    runs-on: ubuntu-latest
    container:
      image: aminamani/ubuntu-raymon:22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show STM32CubeIDE and Firmware paths
        run: |
          echo "STM32CubeIDE Path: $stm32cubeIDE_path"
          echo "Firmware Path: $firmware_path"

      - name: Build with STM32CubeIDE
        run: |
          "$stm32cubeIDE_path" \
            --launcher.suppressErrors \
            -nosplash \
            -application org.eclipse.cdt.managedbuilder.core.headlessbuild \
            -build all \
            -importAll "$firmware_path" \
            -data "$ws_path"
            cd "$firmware_path"
            mkdir build && cd build
            cmake ..
            make
            if [ -f ./test/RunAllTests ]; then ./test/RunAllTests; else echo "Test binary not found! Skipping test run."; fi
            Xvfb :99 -screen 0 1366x768x24 &
            make coverage_report || echo "Coverage report target not found."
            find  / -iname  "Debug"
            find  / -iname  "Release"
            find  / -iname  "coverage_report"
      
      

      - uses: actions/upload-artifact@v4
        if: ${{ hashFiles('firmware/**') != '' }}
        with:
          name: firmware-build
          path: |
            "$firmware_path/Debug/"
            "$firmware_path/Release/"
            "$firmware_path/build/coverage_report"
      
      
      


